// src/components/atoms/radio.tsx
import React, { useState } from 'react';
import Styles from '@styles/modules/radio.module.scss';

interface Props {
	groupName: string;
	checked?: boolean;
	className?: string;
}

const Radio: React.FC<Props> = ({
	groupName = '',
	checked = false,
	className = '',
}) => {
	const [isChecked, setIsChecked] = useState(checked);

	return (
		<input
			x-variant='radio'
			type='radio'
			className={`${className} ${Styles}`}
			name={groupName}
			checked={isChecked}
			onChange={() => {
				setIsChecked(!isChecked);
			}}
		/>
	);
};

export default Radio;

// src/components/atoms/radio.vue
<script setup lang="ts">
	defineProps({
		className: {
			type: String,
			default: '',
		},
		checked: {
			type: Boolean,
			default: false,
		},
		groupName: {
			type: String,
			default: '',
		},
		onChange: {
			type: Function,
		},
	});
</script>

<template>
	<input
		x-variant="radio"
		type="radio"
		:class="[className]"
		name="{groupName}"
		:checked="checked"
		on:change="onChange" />
</template>

<style lang="scss">
	@use '../../commons/styles/modules/radio.scss';
</style>
