// src/components/atoms/spacer.tsx
import type React from 'react';

interface Props {
	direction: string;
	className?: string;
}

const Spacer: React.FC<Props> = ({ direction = '', className = '' }) => {
	return (
		<hr
			className={`align-middle border-none inline-flex flex-shrink min-w-nm ${
				direction === 'horizontal' && 'h-5xs w-full'
			} ${direction === 'vertical' && 'h-full w-5xs'} ${className}`}
		/>
	);
};

export default Spacer;

// src/components/atoms/spacer.vue
<script setup lang="ts">
	import { reactive, ref } from 'vue';

	defineProps({
		className: {
			type: String,
		},
		direction: {
			type: String,
		},
	});

	const direction = ref<string>('');

	const baseClasses =
		'align-middle border-none inline-flex flex-shrink min-w-nm';

	const classes = reactive(() => {
		return `${baseClasses}
	            ${direction.value === 'horizontal' ? 'h-5xs w-full' : ''}
	            ${direction.value === 'vertical' ? 'h-full w-5xs' : ''}`;
	});
</script>

<template>
	<hr :class="[classes]" />
</template>
